# This action allows participants to enroll for the challenge, i.e. get their own instance of the challenge.

name: Enrollment bot

on:  
  issue_comment:
  
permissions: 
  issues: write

env:
  CTF_ORGANIZATION: 'actionsctf23'
  CTF_TEMPLATE_REPO: 'ctf-challenge-template-1'

jobs:  
  enroll-user:
    # Only run if the comment starts with "/enroll"
    if: startsWith(github.event.comment.body, '/enroll')
    runs-on: ubuntu-latest
   
    steps:
      - run: npm install libsodium-wrappers
      - name: Create repository from template
        uses: actions/github-script@v6
        id: create-repo
        with:
          github-token: ${{ secrets.REPO_CREATION_TOKEN }}
          script: |
            const actor_id = process.env.GITHUB_ACTOR_ID;
            const actor = process.env.GITHUB_ACTOR;

            const repoName = `${actor_id}_${actor}_ctf-challenge-1-updt`;
            const repoUrl = `https://github.com/${process.env.CTF_ORGANIZATION}/${repoName}`;

            // catch any errors that might occur, if the repository already exists for example
            try {
              // create a respository from the template repository "CTF_ORGANIZATION/CTF_TEMPLATE_REPO" with the name `github.actor_id`_`github.actor`_ctf-challenge that is private
              var repo = await github.rest.repos.createUsingTemplate({
                template_owner: process.env.CTF_ORGANIZATION,
                template_repo: process.env.CTF_TEMPLATE_REPO,
                owner: process.env.CTF_ORGANIZATION,
                name: repoName,
                private: true
              });
            } catch (error) {
              // if the repository already exists, create a comment on this issue with the link to the repository
              if (error.message.includes('Name already exists on this account')) {
                core.setOutput('message', `@${actor} your repository should already exist at: ${repoUrl}.\n If it doesn't, please open a ticket.`);
                core.warning(`Repository ${repoName} (at: ${repoUrl}) shoud already exist.`)
              } else {
                // if the error is something else, create a comment and then log it
                core.setOutput('message', `@${actor} we could not create a repository for you. Please open a ticket.`);
                core.error(`Repository ${repoName} (at: ${repoUrl}) could not be created.`)
                core.setOutput('failed', 'true');
              }
              console.log(error);
              return;
            }            

            // catch any errors that might occur, create a comment and then log it
            try {
              // add the user as collaborator to the repository with only read aka. pull access
              await github.rest.repos.addCollaborator({
                owner: process.env.CTF_ORGANIZATION,
                repo: repoName,
                username: actor,
                permission: 'pull'
              });
            } catch (error) {
              core.setOutput('message', `@${actor} we could not add you as a collaborator to the repository. Please open a ticket.`);
              core.error(`Failed to add participant to repository: ${repoName} (at: ${repoUrl}).`)
              core.setOutput('failed', 'true');
              console.log(error);
              return;
            }
            core.setOutput('message', `@${actor} your repository is ready at: ${repoUrl}.`);
            
            // Use the github api to get the public key of the repository
            var publicKey
            var key_id
            try {
              const key = await github.rest.actions.getRepoPublicKey({
              owner: process.env.CTF_ORGANIZATION,
              repo: repoName
              });
              console.log(`Public key of ${repoName}:`);
              console.log(key)
              publicKey = key.data.key
              key_id = key.data.key_id
              console.log(publicKey)
              console.log(key_id)
            } catch (error) {
              core.setOutput('message', `@${actor} we could not get the public key of the repository that need we need for adding secrets. Please open a ticket.`);
              core.error(`Failed to get public key needed to add secrets to repository: ${repoName} (at: ${repoUrl}).`)
              core.setOutput('failed', 'true');
              console.log(error);
              return;
            }

            // use the GitHub Api to add a secret with the name "FLAG" to the repository
            try {
              const sodium = require('libsodium-wrappers')
              await sodium.ready;

              const key = publicKey;
              const secret = "${{ secrets.FLAG }}";

              let binkey = sodium.from_base64(key, sodium.base64_variants.ORIGINAL)
              let binsec = sodium.from_string(secret)

              //Encrypt the secret using LibSodium
              let encBytes = sodium.crypto_box_seal(binsec, binkey)

              // Convert encrypted Uint8Array to Base64
              let encrypted_value = sodium.to_base64(encBytes, sodium.base64_variants.ORIGINAL)

              await github.request('PUT /repos/{owner}/{repo}/actions/secrets/{secret_name}', {
                owner: process.env.CTF_ORGANIZATION,
                repo: repoName,
                secret_name: 'FLAG',
                encrypted_value: encrypted_value,
                key_id: key_id,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })
            } catch (error) {
              core.setOutput('message', `@${actor} we could not add the FLAG secret to the repository. Please open a ticket.`);
              core.error(`Failed to add the FLAG secret to repository: ${repoName} (at: ${repoUrl}).`)
              core.setOutput('failed', 'true');
              console.log(error);
              return;
            }



      - name: Post response message
        uses: actions/github-script@v6
        env:
          MESSAGE: ${{ steps.create-repo.outputs.message }}
          FAILED: ${{ steps.create-repo.outputs.failed }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = process.env.MESSAGE;
            const failed = process.env.FAILED;

            // create a comment on this issue with the given message
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
            if(failed === 'true') {
              core.setFailed(message);
            }


